// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTrackAPI.Data;

#nullable disable

namespace VehicleTrackAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415215441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("VehicleTrackAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 15, 21, 54, 41, 428, DateTimeKind.Utc).AddTicks(9502),
                            Make = "Honda",
                            Mileage = 45000,
                            Model = "Civic",
                            Status = "Active",
                            VIN = "1HGCM82633A123456",
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 21, 54, 41, 428, DateTimeKind.Utc).AddTicks(9654),
                            Make = "Toyota",
                            Mileage = 62000,
                            Model = "Corolla",
                            Status = "Maintenance",
                            VIN = "2T1BURHE0JC034567",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 15, 21, 54, 41, 428, DateTimeKind.Utc).AddTicks(9656),
                            Make = "Ford",
                            Mileage = 29000,
                            Model = "F-150",
                            Status = "Active",
                            VIN = "3VWFE21C04M000001",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 15, 21, 54, 41, 428, DateTimeKind.Utc).AddTicks(9657),
                            Make = "Toyota",
                            Mileage = 110000,
                            Model = "Camry",
                            Status = "Retired",
                            VIN = "4T1BF1FK5EU456789",
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 15, 21, 54, 41, 428, DateTimeKind.Utc).AddTicks(9659),
                            Make = "Honda",
                            Mileage = 38000,
                            Model = "Accord",
                            Status = "Active",
                            VIN = "5NPE34AF1FH012345",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
