apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicletrack-api
  labels:
    app: vehicletrack-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicletrack-api
  template:
    metadata:
      labels:
        app: vehicletrack-api
    spec:
      containers:
        - name: vehicletrack-api
          image: vehicletrack-api:latest
          imagePullPolicy: Never        # use local Minikube image
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Data Source=/app/data/vehicletrack.db"
          volumeMounts:
            - name: db-storage
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: db-storage
          emptyDir: {}
