apiVersion: v1
kind: Service
metadata:
  name: vehicletrack-service
  labels:
    app: vehicletrack-api
spec:
  type: NodePort
  selector:
    app: vehicletrack-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
